// KUHUL-ES package entry point
// Exports the canonical Node runtime, browser core, physics engine, trainer,
// thinking engine, pattern reasoner, KXML driver, and chat templates.

const { compress, decompress, compressJSON, decompressJSON } = require('../runtime/src/scxq2.js');
const { KuhulRuntime, KastEngine, KxmlEngine, KuhulConfig, PHASES, EDGE_KINDS, EXPANSION_SPACES, kuhulExecute, kuhul } = require('../runtime/src/unified.js');
const {
  Micronaut,
  Fold,
  Field,
  Tool,
  Gram,
  Agent,
  Rule,
  Registry,
  MicronautRegistry,
  FoldRegistry,
  FieldRegistry,
  ToolRegistry,
  GramRegistry,
  AgentRegistry,
  RuleRegistry,
  MicronautFactory,
  PRIORITIES,
  ROUTING_STRATEGIES,
  MICRONAUT_STATUS,
  PERMISSIONS,
  FOLD_TYPES,
  NODE_TYPES,
  FIELD_TYPES,
  PERSISTENCE,
  ACTION_TYPES,
  AGENT_TYPES,
  MICRONAUT_XJSON_REQUIRED_SECTIONS,
} = require('../runtime/src/micronaut.js');
const {
  CoderDomain,
  InstructorDomain,
  AssistantDomain,
  DomainFactory,
  createCoder,
  createInstructor,
  createAssistant,
} = require('../runtime/src/domains.js');
const { powernautGlslTransport } = require('../runtime/src/transports/powernaut_glsl_transport.js');
const { xvmD3d12Transport, DEFAULT_XVM_DIR } = require('../runtime/src/transports/xvm_d3d12_transport.js');
const { hybridClusterGlslTransport } = require('../runtime/src/transports/hybrid_cluster_glsl_transport.js');
const { ChatBridge } = require('../runtime/src/chat_bridge.js');
const { KUHULEngine } = require('../runtime/src/kuhul-e.js');
const { DomainStack } = require('../runtime/src/domain-stack.js');
const { ResponsePatternEngine } = require('../runtime/src/response-pattern.js');
const { KUHULRuntimeNode } = require('../runtime/src/node.js');
const { KuhulPhysics } = require('../runtime/src/physics.js');
const { GLSLTrainer, glslHttpTransport } = require('../runtime/src/trainer.js');
const { KuhulThinkEngine, DEFAULT_RULES } = require('../runtime/src/think.js');
const { SemanticPatternReasoner } = require('../runtime/src/pattern_reasoner.js');
const { SemanticTrainer, DEFAULT_TRAINING_RULES } = require('../runtime/src/trainer_semantic.js');
const { RuntimeParser } = require('../runtime/src/runtime_parser.js');
const { ExpressionEvaluator } = require('../runtime/src/expression_evaluator.js');
const { KxmlModel, opEmbed, opLayerNorm, opMatmul, opGelu, opAttention, GLYPH_TO_FOLD } = require('../runtime/src/kxml_driver.js');
const { readStb, readStbFile } = require('../runtime/src/stb_reader.js');
const { toJinja, emitTemplate, renderForGguf, renderJinja } = require('../runtime/src/kxml_chat.js');
const { KUHULRuntimeCore, hashState, DEFAULT_GLYPHS } = require('../runtime/src/core.js');
const { FoldEngine } = require('../runtime/src/fold-engine.js');
const { loadTokenizer, simpleCharTokenizer } = require('../runtime/src/tokenizer.js');
const {
  SkeletonTemplate,
  NeuralNetworkTemplates,
  DomainSkeletons,
  SkeletonFactory,
  createMLP,
  createCNN,
  createRNN,
  createLSTM,
  createTransformer,
  createNLP,
  createVision,
  createAudio,
  createGNN,
} = require('../runtime/src/skeleton_templates.js');
const {
  MicronautBridge,
  TransportBridge,
  PowernautBridge,
  XvmD3d12Bridge,
  HybridClusterGlslBridge,
  FileSystemBridge,
  HttpBridge,
  MessageQueueBridge,
  BridgeFactory,
  createBridge,
} = require('../runtime/src/micronaut_bridges.js');
const {
  buildTokenDataset,
  buildChatJsonlTokenDataset,
  datasetToInt32Tensors,
  extractChatTextFromRecord,
} = require('../runtime/src/text_dataset.js');

module.exports = {
  compress,
  decompress,
  compressJSON,
  decompressJSON,
  kuhulExecute,
  kuhul,
  KuhulRuntime,
  KastEngine,
  KxmlEngine,
  KuhulConfig,
  PHASES,
  EDGE_KINDS,
  EXPANSION_SPACES,
  Micronaut,
  Fold,
  Field,
  Tool,
  Gram,
  Agent,
  Rule,
  Registry,
  MicronautRegistry,
  FoldRegistry,
  FieldRegistry,
  ToolRegistry,
  GramRegistry,
  AgentRegistry,
  RuleRegistry,
  MicronautFactory,
  PRIORITIES,
  ROUTING_STRATEGIES,
  MICRONAUT_STATUS,
  PERMISSIONS,
  FOLD_TYPES,
  NODE_TYPES,
  FIELD_TYPES,
  PERSISTENCE,
  ACTION_TYPES,
  AGENT_TYPES,
  MICRONAUT_XJSON_REQUIRED_SECTIONS,
  CoderDomain,
  InstructorDomain,
  AssistantDomain,
  DomainFactory,
  createCoder,
  createInstructor,
  createAssistant,
  powernautGlslTransport,
  hybridClusterGlslTransport,
  xvmD3d12Transport,
  DEFAULT_XVM_DIR,
  ChatBridge,
  KUHULEngine,
  DomainStack,
  ResponsePatternEngine,
  FoldEngine,
  loadTokenizer,
  simpleCharTokenizer,
  SkeletonTemplate,
  NeuralNetworkTemplates,
  DomainSkeletons,
  SkeletonFactory,
  createMLP,
  createCNN,
  createRNN,
  createLSTM,
  createTransformer,
  createNLP,
  createVision,
  createAudio,
  createGNN,
  MicronautBridge,
  TransportBridge,
  PowernautBridge,
  XvmD3d12Bridge,
  HybridClusterGlslBridge,
  FileSystemBridge,
  HttpBridge,
  MessageQueueBridge,
  BridgeFactory,
  createBridge,
  buildTokenDataset,
  buildChatJsonlTokenDataset,
  datasetToInt32Tensors,
  extractChatTextFromRecord,
  KUHULRuntimeNode,
  KUHULRuntimeCore,
  KuhulPhysics,
  GLSLTrainer,
  glslHttpTransport,
  KuhulThinkEngine,
  SemanticPatternReasoner,
  SemanticTrainer,
  RuntimeParser,
  ExpressionEvaluator,
  KxmlModel,
  opEmbed,
  opLayerNorm,
  opMatmul,
  opGelu,
  opAttention,
  GLYPH_TO_FOLD,
  readStb,
  readStbFile,
  toJinja,
  emitTemplate,
  renderForGguf,
  renderJinja,
  hashState,
  DEFAULT_GLYPHS,
  DEFAULT_TRAINING_RULES,
  DEFAULT_RULES,
};
